language: ruby

env:
  global:
    - machine_user=travis
    - machine_pass=travis
    - machine_port=22
    - KITCHEN_YAML=.kitchen.travis.yml

rvm:
  - 2.3.0

sudo: required
dist: trusty

before_install:
  - sudo usermod -p "`openssl passwd -1 'travis'`" travis
  - sudo apt-get update

script:
  - bundle exec rspec
  - bundle exec kitchen verify


branches:
  only:
  - master
