language: ruby
cache: bundler
sudo: false
services: docker

rvm:
  - 2.3.0

env:
  global:
    - KITCHEN_YAML=.kitchen.docker.yml

  matrix:
    - TEST_SUITE=percona-server-ubuntu-1404
    - TEST_SUITE=percona-xtradb-ubuntu-1404

before_install:
  - test/travis_ci/lvm_setup.bash 2>&1

script:
  - bundle exec rspec
  - bundle exec kitchen verify ${TEST_SUITE}


branches:
  only:
  - master
